title: dump(Celan)
author:
  name: SeungJun Lee(Celan)
  email: sollleky72@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  개발 및 개발 설계에서 생기는 고민들과 문제를 해결하는 과정을 기록합니다. 

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
include:
  - _pages

# Theme-specific settings

minima:
  skin: "dark"
  date_format: "%Y-%m-%d"

  social_links:
    - { platform: github,         user_url: "https://github.com/valselee" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/celanlee" }

header_pages:
  - _pages/about.md

# show_excerpts: true
